
name: Get version
description: Get the version information from the repository
inputs:
  version-file-path:
    description: Path of version file
    required: true

outputs:
  version-prefix:
    description: "The version prefix"
    value: ${{ steps.get-version.outputs.version-prefix }}

  version-suffix:
    description: "The version suffix"
    value: ${{ steps.get-version.outputs.version-suffix }}

  version-package:
    description: "The full package version"
    value: ${{ steps.get-version.outputs.version-package }}

  version-major:
    description: "The major version"
    value: ${{ steps.get-version.outputs.version-major }}

  version-minor:
    description: "The minor version"
    value: ${{ steps.get-version.outputs.version-minor }}

runs:
  using: "composite"
  steps:
    - name: Install xmllint
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y libxml2-utils

    - name: get version
      id: get-version
      shell: bash
      run: |
        VERSION_FILE_PATH=${{ inputs.version-file-path }}
        VERSION_PREFIX=$(xmllint --xpath "string(/Project/PropertyGroup/VersionPrefix)" "${VERSION_FILE_PATH}")
        VERSION_SUFFIX=$(xmllint --xpath "string(/Project/PropertyGroup/VersionSuffix)" "${VERSION_FILE_PATH}")

        VERSION_PATCH=$(git rev-list --count HEAD)
        VERSION_PREFIX="${VERSION_PREFIX}.${VERSION_PATCH}"

        if [ -n "$VERSION_SUFFIX" ]; then
          VERSION_PACKAGE="${VERSION_PREFIX}-${VERSION_SUFFIX}"
        else
          VERSION_PACKAGE="$VERSION_PREFIX"
        fi

        VERSION_MAJOR=$(echo "$VERSION_PREFIX" | cut -d. -f1)
        VERSION_MINOR=$(echo "$VERSION_PREFIX" | cut -d. -f2)

        echo "VERSION_PREFIX = ${VERSION_PREFIX}"
        echo "VERSION_SUFFIX = ${VERSION_SUFFIX}"
        echo "VERSION_PACKAGE = ${VERSION_PACKAGE}"
        echo "VERSION_MAJOR = ${VERSION_MAJOR}"
        echo "VERSION_MINOR = ${VERSION_MINOR}"

        echo "version-prefix=$VERSION_PREFIX" >> $GITHUB_OUTPUT
        echo "version-suffix=$VERSION_SUFFIX" >> $GITHUB_OUTPUT
        echo "version-package=$VERSION_PACKAGE" >> $GITHUB_OUTPUT
        echo "version-major=$VERSION_MAJOR" >> $GITHUB_OUTPUT
        echo "version-minor=$VERSION_MINOR" >> $GITHUB_OUTPUT
